### ISSUE TITLE
Character Embedding

### ISSUE THREAD

**Issue by arxrean** [boenninghoff/AdHominem#1]
Thank you for your sharing. Could you please help to point out where you get the initial character embeddings? (Such as encode 'A' to a D_r embedding). Do you use a learnable embedding layer for it? Thank you!

**Comment by boenninghoff** [comment]
Hi, 
thank you for your interest! 

I just randomly initialized the character embeddings. You can find this piece of code in lines 163 - 174 of the function "AdHominem/training/initialize_placeholders.py".

By the way, I'm planning to update a modified and faster version of AdHominem in two weeks, when the software submission period of PAN is over.

Best,
Benedikt

**Comment by arxrean** [comment]
Thank you!
That's great. Look forward to it!

**Comment by boenninghoff** [comment]
Hey,
I am sorry for late feedback.
I updated the repository. The code should work faster and with less memory now.
I'll close the issue. If you have additional questions, you can open another issue. :) 
Best,
Benedikt
