### ISSUE TITLE
Corpus

### ISSUE THREAD

**Issue by ItsDefinetlyNotMe** [boenninghoff/AdHominem#4]
Dear Mr boenninghoff,
As i could not reach you per email i am trying to reach you this way as a last try.
I am currently working for the Bauhaus University Weimar and was looking into some Research regarding Authorship Verification. In the paper “Explainable Authorship Verification in Social Media via Attention-based Similarity Learning“ you mentioned a newly compiled Corpus of Amazon short reviews, and i wanted to kindly ask you wether you are willing to grant me access to that corpus. As we are testing different Methods amongst others your presented model. 
Best regards,
Simon Förster

**Comment by boenninghoff** [comment]
Hi Simon Förster,
I wrote you an email. If you did not receive an email, please write me again. :)
Best
Benedikt
